### ISSUE TITLE
Trying to work with xmledit

### ISSUE THREAD

**Issue by Ziiweb** [sukima/xmledit#19]
Hi

I have installed vim and then i copied the `xml.vim` file inside `~/.vim/ftplugin`.

Then I open a `.xml` file but after writing `<foobar>` it doesn't autocomplete the closing tag..

Any help?

**Comment by jdejoode** [comment]
I have the same issue but I am using vundle.

In .vimrc I have

      1 set nocompatible
      2 filetype off
      3 
      4 let mapleader = ","
      5 
      6 " set the runtime path to include Vundle and initialize
      7 set rtp+=~/.vim/bundle/Vundle.vim
      8 call vundle#begin()
      9 " alternatively, pass a path where Vundle should install plugins
     10 " call vundle#begin('~/some/path/here')
     11 
     12 " " let Vundle manage Vundle, required
     13 Plugin 'VundleVim/Vundle.vim'
     14 
     15 " My manually inserted B/Vundles
     16 Plugin 'sukima/xmledit'
    ...
     98 call vundle#end()            " required
     99 filetype plugin indent on    " required


and the filetype is xml.

Can you document how you install it using Vundle?

**Comment by albertdev** [comment]
@jdejoode 
Did you remember to run `:PluginInstall`? Did the log of that command show any red output to signal an error?

Can you check your home folder to see if `~/.vim/bundle/` has a folder `xmledit`?

**Comment by jdejoode** [comment]
Yes I ran :PluginInstall and yes I have a ~/.vim/bundle folder which contains xmledit

any other suggestion?
thanks

Date: Sat, 10 Oct 2015 05:18:55 -0700

**Comment by albertdev** [comment]
@jdejoode 
You could try to verify if xmledit is even loaded at all by opening an XML file in a fresh (g)Vim instance and then peering through the output of `:scriptnames` (it should be towards the end as plugins are loaded before filetype-plugins).

If it isn't there you might need to check `:set filetype?` to see if your file is being recognized as something else.

If it *is* there you might need to do a few more checks, e.g. see what `:set paste?` returns or see if you have any plugins which might conflict with xmledit.

**Comment by sukima** [comment]
@albertdev Thanks for fielding that.
