### ISSUE TITLE
Problem with closing bracket ending up 1 character to the right

### ISSUE THREAD

**Issue by marlun** [sukima/xmledit#44]
After 781eccae0da8eca4685d53d384cef1dce14403f3 I'm having problems with xmledit and smarty files. I've added smarty_xmledit.vim in my ftplugin so that it's loaded for my smarty files however when I write `{if $object-|}` (where | means where the caret is) and hit `>` I end up with `{if $object-}>|` instead of `{if $object->|}` which makes it impossible to do anything :)

If I'm not misunderstanding it's the new `execute "normal! l"` that is causing problems for me.

**Comment by sukima** [comment]
Hmmm. does sound like a bug. I had thought the function was a no op if the cursor was inside a different syntax group other then XML or HTML. Any suggestions how we could mitigate this one?

**Comment by marlun** [comment]
I'll see if I can take a closer look at it later today or this weekend.

**Comment by exitface** [comment]
+1 Having the same issue. If I revert to version 1.10.4 it works correctly
